/**
 * VROOOOM RACING
 * 
 * Copyright 2012 Zach "theY4Kman" Kanzler
 */

#if defined _wintox_race_included
 #endinput
#endif
#define _wintox_race_included


Race_Init()
{
}

Race_DeinitPlayer(client)
{
}

// Bring up a menu of all players in the server for the challenger to choose
// their challengee.
AskRace(challenger)
{
}

// Setup the players at the start zone and begin the countdown timer
InitiateRace(challenger, challengee)
{
}
